# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.dashboards_api import DashboardsApi  # noqa: E501


class TestDashboardsApi(unittest.TestCase):
    """DashboardsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DashboardsApi()

    def tearDown(self) -> None:
        pass

    def test_create_dashboard(self) -> None:
        """Test case for create_dashboard

        Creates new dashboard  # noqa: E501
        """
        pass

    def test_get_all_dashboards(self) -> None:
        """Test case for get_all_dashboards

        Returns paged collection of all Dashboards in a project  # noqa: E501
        """
        pass

    def test_get_dashboard_by_id(self) -> None:
        """Test case for get_dashboard_by_id

        Gets dashboard by id  # noqa: E501
        """
        pass

    def test_update_dashboard_by_id(self) -> None:
        """Test case for update_dashboard_by_id

        Updates dashboard by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
