# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.view_paged_model_dto import ViewPagedModelDTO  # noqa: E501

class TestViewPagedModelDTO(unittest.TestCase):
    """ViewPagedModelDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ViewPagedModelDTO:
        """Test ViewPagedModelDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ViewPagedModelDTO`
        """
        model = ViewPagedModelDTO()  # noqa: E501
        if include_optional:
            return ViewPagedModelDTO(
                content = [
                    openapi_client.models.view_dto.ViewDTO(
                        id = '', 
                        name = 'awat5ikwowtta-3mh2lcafqw3zhes', 
                        type = 'dataset', 
                        title = '0', 
                        description = '', 
                        content = openapi_client.models.view_content_dto.ViewContentDTO(
                            icon = 'q', 
                            dashboard = '/rest/projects/8q6zgckec0l3o4gi/md/dashboards?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc', 
                            map = '/rest/projects/8q6zgckec0l3o4gi/md/maps?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc', 
                            marker_selector = '/rest/projects/8q6zgckec0l3o4gi/md/markerSelectors?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc', 
                            markers_only = True, 
                            show_attributes_on_drill = True, 
                            default_granularity = '/rest/projects/8q6zgckec0l3o4gi/md/datasets?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc', 
                            default_visualized = '/rest/projects/8q6zgckec0l3o4gi/md/indicators?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc', 
                            default_visualization = 'areas', 
                            default_drilled = '/rest/projects/8q6zgckec0l3o4gi/md/indicators?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc', 
                            default_tool = 'search', 
                            default_compare_type = 'dominance', 
                            compare_collapsed = True, 
                            filter_group = [
                                null
                                ], 
                            default_active_filters = [
                                null
                                ], 
                            variables = [
                                openapi_client.models.variables_dto.VariablesDTO(
                                    type = 'variables', 
                                    title = '0', 
                                    variables = [
                                        openapi_client.models.variable_dto.VariableDTO(
                                            name = 'awat5ikwowtta-3mh2lcafqw3zhes', 
                                            title = '0', 
                                            min_value = 1.337, 
                                            max_value = 1.337, 
                                            default_value = 1.337, 
                                            format = openapi_client.models.format_dto.FormatDTO(
                                                type = 'number', 
                                                fraction = 0, 
                                                symbol = '', ), )
                                        ], )
                                ], 
                            spatial_query = openapi_client.models.isochrone_dto.IsochroneDTO(
                                lat = -180.0, 
                                lng = -180.0, 
                                profile = 'car', 
                                unit = 'time', 
                                amount = 1, 
                                geometry = null, ), 
                            fitness_groups = 3, 
                            map_options = openapi_client.models.map_options_dto.MapOptionsDTO(
                                center = openapi_client.models.center_dto.CenterDTO(
                                    lat = 1.337, 
                                    lng = 1.337, ), 
                                zoom = 56, 
                                min_zoom = 0, 
                                max_zoom = 56, 
                                tile_layer_menu = True, 
                                tile_layer = 'mapbox', 
                                custom_tile_layer = openapi_client.models.map_options_dto_custom_tile_layer.MapOptionsDTO_customTileLayer(
                                    url = 'mapbox://styles/jUR,rZ#UM/?R,Fp^l6$ARj', 
                                    access_token = '0', ), ), 
                            map_context_menu = openapi_client.models.map_context_menu_dto.MapContextMenuDTO(
                                items = [
                                    null
                                    ], ), 
                            exports = [
                                openapi_client.models.export_link_dto.ExportLinkDTO(
                                    export = '/rest/projects/8q6zgckec0l3o4gi/md/exports?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc', )
                                ], 
                            measure = openapi_client.models.measure_dto.MeasureDTO(
                                type = 'line', 
                                points = [
                                    openapi_client.models.isochrone_dto.IsochroneDTO(
                                        lat = -180.0, 
                                        lng = -180.0, 
                                        profile = 'car', 
                                        unit = 'time', 
                                        amount = 1, 
                                        geometry = null, )
                                    ], 
                                zones = [
                                    
                                    ], ), 
                            default_selected = openapi_client.models.default_selected_dto.DefaultSelectedDTO(
                                dataset = '/rest/projects/8q6zgckec0l3o4gi/md/datasets?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc', 
                                ids = [
                                    null
                                    ], 
                                coordinates = [
                                    openapi_client.models.center_dto.CenterDTO(
                                        lat = 1.337, 
                                        lng = 1.337, )
                                    ], ), 
                            exclude_datasets = [
                                ''
                                ], 
                            disable_fitness = True, ), )
                    ],
                links = [
                    None
                    ],
                page = openapi_client.models.mandatory_keys_for_pagable_response.mandatory keys for pagable response(
                    size = 56, 
                    total_elements = null, 
                    total_pages = 56, 
                    number = 56, )
            )
        else:
            return ViewPagedModelDTO(
        )
        """

    def testViewPagedModelDTO(self):
        """Test ViewPagedModelDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
