# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.active_multi_select_filter_dto import ActiveMultiSelectFilterDTO  # noqa: E501

class TestActiveMultiSelectFilterDTO(unittest.TestCase):
    """ActiveMultiSelectFilterDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActiveMultiSelectFilterDTO:
        """Test ActiveMultiSelectFilterDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActiveMultiSelectFilterDTO`
        """
        model = ActiveMultiSelectFilterDTO()  # noqa: E501
        if include_optional:
            return ActiveMultiSelectFilterDTO(
                default_values = openapi_client.models.default_values_multi_select_dto.DefaultValuesMultiSelectDTO(
                    values = [
                        null
                        ], ),
                type = 'multiSelect',
                var_property = '',
                order_by = [
                    openapi_client.models.order_by_dto.OrderByDTO(
                        property = '', 
                        direction = 'asc', )
                    ]
            )
        else:
            return ActiveMultiSelectFilterDTO(
                default_values = openapi_client.models.default_values_multi_select_dto.DefaultValuesMultiSelectDTO(
                    values = [
                        null
                        ], ),
                type = 'multiSelect',
                var_property = '',
        )
        """

    def testActiveMultiSelectFilterDTO(self):
        """Test ActiveMultiSelectFilterDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
