# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.indicator_group_dto import IndicatorGroupDTO  # noqa: E501

class TestIndicatorGroupDTO(unittest.TestCase):
    """IndicatorGroupDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IndicatorGroupDTO:
        """Test IndicatorGroupDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IndicatorGroupDTO`
        """
        model = IndicatorGroupDTO()  # noqa: E501
        if include_optional:
            return IndicatorGroupDTO(
                type = 'indicatorGroup',
                title = '0',
                description = '',
                collapsed = True,
                block_rows = [
                    null
                    ]
            )
        else:
            return IndicatorGroupDTO(
                type = 'indicatorGroup',
                title = '0',
                block_rows = [
                    null
                    ],
        )
        """

    def testIndicatorGroupDTO(self):
        """Test IndicatorGroupDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
