# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.mapycz_ortophoto_dto import MapyczOrtophotoDTO  # noqa: E501

class TestMapyczOrtophotoDTO(unittest.TestCase):
    """MapyczOrtophotoDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MapyczOrtophotoDTO:
        """Test MapyczOrtophotoDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MapyczOrtophotoDTO`
        """
        model = MapyczOrtophotoDTO()  # noqa: E501
        if include_optional:
            return MapyczOrtophotoDTO(
                type = 'mapyczOrtophoto'
            )
        else:
            return MapyczOrtophotoDTO(
        )
        """

    def testMapyczOrtophotoDTO(self):
        """Test MapyczOrtophotoDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
