# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.default_values_date_dto import DefaultValuesDateDTO  # noqa: E501

class TestDefaultValuesDateDTO(unittest.TestCase):
    """DefaultValuesDateDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultValuesDateDTO:
        """Test DefaultValuesDateDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultValuesDateDTO`
        """
        model = DefaultValuesDateDTO()  # noqa: E501
        if include_optional:
            return DefaultValuesDateDTO(
                start_date = None,
                end_date = None
            )
        else:
            return DefaultValuesDateDTO(
        )
        """

    def testDefaultValuesDateDTO(self):
        """Test DefaultValuesDateDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
