# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.default_values_feature_dto import DefaultValuesFeatureDTO  # noqa: E501

class TestDefaultValuesFeatureDTO(unittest.TestCase):
    """DefaultValuesFeatureDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultValuesFeatureDTO:
        """Test DefaultValuesFeatureDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultValuesFeatureDTO`
        """
        model = DefaultValuesFeatureDTO()  # noqa: E501
        if include_optional:
            return DefaultValuesFeatureDTO(
                values = [
                    ''
                    ]
            )
        else:
            return DefaultValuesFeatureDTO(
                values = [
                    ''
                    ],
        )
        """

    def testDefaultValuesFeatureDTO(self):
        """Test DefaultValuesFeatureDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
