# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.format_dto import FormatDTO  # noqa: E501

class TestFormatDTO(unittest.TestCase):
    """FormatDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormatDTO:
        """Test FormatDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormatDTO`
        """
        model = FormatDTO()  # noqa: E501
        if include_optional:
            return FormatDTO(
                type = 'number',
                fraction = 0,
                symbol = ''
            )
        else:
            return FormatDTO(
                type = 'number',
        )
        """

    def testFormatDTO(self):
        """Test FormatDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
