# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.active_indicator_filter_dto import ActiveIndicatorFilterDTO  # noqa: E501

class TestActiveIndicatorFilterDTO(unittest.TestCase):
    """ActiveIndicatorFilterDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActiveIndicatorFilterDTO:
        """Test ActiveIndicatorFilterDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActiveIndicatorFilterDTO`
        """
        model = ActiveIndicatorFilterDTO()  # noqa: E501
        if include_optional:
            return ActiveIndicatorFilterDTO(
                default_values = openapi_client.models.default_values_indicator_dto.DefaultValuesIndicatorDTO(
                    values = [
                        1.337
                        ], 
                    breaks = [
                        1.337
                        ], 
                    display_intervals = [
                        56
                        ], 
                    granularity = '/rest/projects/8q6zgckec0l3o4gi/md/datasets?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc', ),
                type = 'indicator',
                indicator = '/rest/projects/8q6zgckec0l3o4gi/md/indicators?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc',
                filter_selection = True
            )
        else:
            return ActiveIndicatorFilterDTO(
                default_values = openapi_client.models.default_values_indicator_dto.DefaultValuesIndicatorDTO(
                    values = [
                        1.337
                        ], 
                    breaks = [
                        1.337
                        ], 
                    display_intervals = [
                        56
                        ], 
                    granularity = '/rest/projects/8q6zgckec0l3o4gi/md/datasets?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc', ),
                type = 'indicator',
                indicator = '/rest/projects/8q6zgckec0l3o4gi/md/indicators?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc',
        )
        """

    def testActiveIndicatorFilterDTO(self):
        """Test ActiveIndicatorFilterDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
