# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.date_filter_default_value_type import DateFilterDefaultValueType  # noqa: E501

class TestDateFilterDefaultValueType(unittest.TestCase):
    """DateFilterDefaultValueType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DateFilterDefaultValueType:
        """Test DateFilterDefaultValueType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DateFilterDefaultValueType`
        """
        model = DateFilterDefaultValueType()  # noqa: E501
        if include_optional:
            return DateFilterDefaultValueType(
                value = '0',
                function = openapi_client.models.function.function()
            )
        else:
            return DateFilterDefaultValueType(
                value = '0',
                function = openapi_client.models.function.function(),
        )
        """

    def testDateFilterDefaultValueType(self):
        """Test DateFilterDefaultValueType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
