# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.default_values_histogram_dto import DefaultValuesHistogramDTO  # noqa: E501

class TestDefaultValuesHistogramDTO(unittest.TestCase):
    """DefaultValuesHistogramDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultValuesHistogramDTO:
        """Test DefaultValuesHistogramDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultValuesHistogramDTO`
        """
        model = DefaultValuesHistogramDTO()  # noqa: E501
        if include_optional:
            return DefaultValuesHistogramDTO(
                values = [
                    1.337
                    ],
                null_filtered = True
            )
        else:
            return DefaultValuesHistogramDTO(
        )
        """

    def testDefaultValuesHistogramDTO(self):
        """Test DefaultValuesHistogramDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
