# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.measure_dto import MeasureDTO  # noqa: E501

class TestMeasureDTO(unittest.TestCase):
    """MeasureDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MeasureDTO:
        """Test MeasureDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeasureDTO`
        """
        model = MeasureDTO()  # noqa: E501
        if include_optional:
            return MeasureDTO(
                type = 'line',
                points = [
                    openapi_client.models.isochrone_dto.IsochroneDTO(
                        lat = -180.0, 
                        lng = -180.0, 
                        profile = 'car', 
                        unit = 'time', 
                        amount = 1, 
                        geometry = null, )
                    ],
                zones = [
                    openapi_client.models.isochrone_dto.IsochroneDTO(
                        lat = -180.0, 
                        lng = -180.0, 
                        profile = 'car', 
                        unit = 'time', 
                        amount = 1, 
                        geometry = null, )
                    ]
            )
        else:
            return MeasureDTO(
        )
        """

    def testMeasureDTO(self):
        """Test MeasureDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
