# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.mandatory_keys_for_pagable_response import MandatoryKeysForPagableResponse  # noqa: E501

class TestMandatoryKeysForPagableResponse(unittest.TestCase):
    """MandatoryKeysForPagableResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MandatoryKeysForPagableResponse:
        """Test MandatoryKeysForPagableResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MandatoryKeysForPagableResponse`
        """
        model = MandatoryKeysForPagableResponse()  # noqa: E501
        if include_optional:
            return MandatoryKeysForPagableResponse(
                size = 56,
                total_elements = None,
                total_pages = 56,
                number = 56
            )
        else:
            return MandatoryKeysForPagableResponse(
                size = 56,
                total_elements = None,
                total_pages = 56,
                number = 56,
        )
        """

    def testMandatoryKeysForPagableResponse(self):
        """Test MandatoryKeysForPagableResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
