# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.variables_dto import VariablesDTO  # noqa: E501

class TestVariablesDTO(unittest.TestCase):
    """VariablesDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariablesDTO:
        """Test VariablesDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariablesDTO`
        """
        model = VariablesDTO()  # noqa: E501
        if include_optional:
            return VariablesDTO(
                type = 'variables',
                title = '0',
                variables = [
                    openapi_client.models.variable_dto.VariableDTO(
                        name = 'awat5ikwowtta-3mh2lcafqw3zhes', 
                        title = '0', 
                        min_value = 1.337, 
                        max_value = 1.337, 
                        default_value = 1.337, 
                        format = openapi_client.models.format_dto.FormatDTO(
                            type = 'number', 
                            fraction = 0, 
                            symbol = '', ), )
                    ]
            )
        else:
            return VariablesDTO(
                type = 'variables',
                title = '0',
                variables = [
                    openapi_client.models.variable_dto.VariableDTO(
                        name = 'awat5ikwowtta-3mh2lcafqw3zhes', 
                        title = '0', 
                        min_value = 1.337, 
                        max_value = 1.337, 
                        default_value = 1.337, 
                        format = openapi_client.models.format_dto.FormatDTO(
                            type = 'number', 
                            fraction = 0, 
                            symbol = '', ), )
                    ],
        )
        """

    def testVariablesDTO(self):
        """Test VariablesDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
