# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.map_options_dto import MapOptionsDTO  # noqa: E501

class TestMapOptionsDTO(unittest.TestCase):
    """MapOptionsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MapOptionsDTO:
        """Test MapOptionsDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MapOptionsDTO`
        """
        model = MapOptionsDTO()  # noqa: E501
        if include_optional:
            return MapOptionsDTO(
                center = openapi_client.models.center_dto.CenterDTO(
                    lat = 1.337, 
                    lng = 1.337, ),
                zoom = 56,
                min_zoom = 0,
                max_zoom = 56,
                tile_layer_menu = True,
                tile_layer = 'mapbox',
                custom_tile_layer = openapi_client.models.map_options_dto_custom_tile_layer.MapOptionsDTO_customTileLayer(
                    url = 'mapbox://styles/jUR,rZ#UM/?R,Fp^l6$ARj', 
                    access_token = '0', )
            )
        else:
            return MapOptionsDTO(
        )
        """

    def testMapOptionsDTO(self):
        """Test MapOptionsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
