# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.ranking_dto import RankingDTO  # noqa: E501

class TestRankingDTO(unittest.TestCase):
    """RankingDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RankingDTO:
        """Test RankingDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RankingDTO`
        """
        model = RankingDTO()  # noqa: E501
        if include_optional:
            return RankingDTO(
                type = 'ranking',
                title = '',
                indicator = '/rest/projects/8q6zgckec0l3o4gi/md/indicators?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc',
                default_layer = 'awat5ikwowtta-3mh2lcafqw3zhes',
                feature_type = 'granularity',
                direction = 'asc',
                collapsed = True,
                visualized = True
            )
        else:
            return RankingDTO(
                type = 'ranking',
        )
        """

    def testRankingDTO(self):
        """Test RankingDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
