# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.views_api import ViewsApi  # noqa: E501


class TestViewsApi(unittest.TestCase):
    """ViewsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ViewsApi()

    def tearDown(self) -> None:
        pass

    def test_create_view(self) -> None:
        """Test case for create_view

        Creates new view  # noqa: E501
        """
        pass

    def test_delete_dashboard_by_id(self) -> None:
        """Test case for delete_dashboard_by_id

        Deletes dashboard by id  # noqa: E501
        """
        pass

    def test_delete_view_by_id(self) -> None:
        """Test case for delete_view_by_id

        Deletes view by id  # noqa: E501
        """
        pass

    def test_get_all_views(self) -> None:
        """Test case for get_all_views

        Returns collection of all views in a project  # noqa: E501
        """
        pass

    def test_get_view_by_id(self) -> None:
        """Test case for get_view_by_id

        Gets view by id  # noqa: E501
        """
        pass

    def test_update_view_by_id(self) -> None:
        """Test case for update_view_by_id

        Updates view by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
