# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.variable_dto import VariableDTO  # noqa: E501

class TestVariableDTO(unittest.TestCase):
    """VariableDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariableDTO:
        """Test VariableDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariableDTO`
        """
        model = VariableDTO()  # noqa: E501
        if include_optional:
            return VariableDTO(
                name = 'awat5ikwowtta-3mh2lcafqw3zhes',
                title = '0',
                min_value = 1.337,
                max_value = 1.337,
                default_value = 1.337,
                format = openapi_client.models.format_dto.FormatDTO(
                    type = 'number', 
                    fraction = 0, 
                    symbol = '', )
            )
        else:
            return VariableDTO(
                name = 'awat5ikwowtta-3mh2lcafqw3zhes',
                title = '0',
                min_value = 1.337,
                max_value = 1.337,
                default_value = 1.337,
                format = openapi_client.models.format_dto.FormatDTO(
                    type = 'number', 
                    fraction = 0, 
                    symbol = '', ),
        )
        """

    def testVariableDTO(self):
        """Test VariableDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
