# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist, constr, validator
from openapi_client.models.default_values_single_select_dto import DefaultValuesSingleSelectDTO
from openapi_client.models.order_by_dto import OrderByDTO

class ActiveSingleSelectFilterDTO(BaseModel):
    """
    ActiveSingleSelectFilterDTO
    """
    default_values: DefaultValuesSingleSelectDTO = Field(default=..., alias="defaultValues")
    type: constr(strict=True) = Field(...)
    var_property: StrictStr = Field(default=..., alias="property")
    order_by: Optional[conlist(OrderByDTO)] = Field(default=None, alias="orderBy")
    __properties = ["defaultValues", "type", "property", "orderBy"]

    @validator('type')
    def type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^singleSelect$", value):
            raise ValueError(r"must validate the regular expression /^singleSelect$/")
        return value

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('singleSelect'):
            raise ValueError("must be one of enum values ('singleSelect')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ActiveSingleSelectFilterDTO:
        """Create an instance of ActiveSingleSelectFilterDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of default_values
        if self.default_values:
            _dict['defaultValues'] = self.default_values.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in order_by (list)
        _items = []
        if self.order_by:
            for _item in self.order_by:
                if _item:
                    _items.append(_item.to_dict())
            _dict['orderBy'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ActiveSingleSelectFilterDTO:
        """Create an instance of ActiveSingleSelectFilterDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ActiveSingleSelectFilterDTO.parse_obj(obj)

        _obj = ActiveSingleSelectFilterDTO.parse_obj({
            "default_values": DefaultValuesSingleSelectDTO.from_dict(obj.get("defaultValues")) if obj.get("defaultValues") is not None else None,
            "type": obj.get("type"),
            "var_property": obj.get("property"),
            "order_by": [OrderByDTO.from_dict(_item) for _item in obj.get("orderBy")] if obj.get("orderBy") is not None else None
        })
        return _obj


