# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, conint, validator

class AttributeFormatDTO(BaseModel):
    """
    AttributeFormatDTO
    """
    type: StrictStr = Field(...)
    fraction: Optional[conint(strict=True, ge=0)] = None
    symbol: Optional[StrictStr] = None
    __properties = ["type", "fraction", "symbol"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('text', 'number', 'percentage', 'email', 'link'):
            raise ValueError("must be one of enum values ('text', 'number', 'percentage', 'email', 'link')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AttributeFormatDTO:
        """Create an instance of AttributeFormatDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AttributeFormatDTO:
        """Create an instance of AttributeFormatDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AttributeFormatDTO.parse_obj(obj)

        _obj = AttributeFormatDTO.parse_obj({
            "type": obj.get("type") if obj.get("type") is not None else 'text',
            "fraction": obj.get("fraction"),
            "symbol": obj.get("symbol")
        })
        return _obj


