# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist, constr, validator
from openapi_client.models.indicator_link_dto import IndicatorLinkDTO

class BlockRowDTO(BaseModel):
    """
    BlockRowDTO
    """
    type: constr(strict=True) = Field(...)
    blocks: conlist(IndicatorLinkDTO) = Field(...)
    __properties = ["type", "blocks"]

    @validator('type')
    def type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^blockRow$", value):
            raise ValueError(r"must validate the regular expression /^blockRow$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BlockRowDTO:
        """Create an instance of BlockRowDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in blocks (list)
        _items = []
        if self.blocks:
            for _item in self.blocks:
                if _item:
                    _items.append(_item.to_dict())
            _dict['blocks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BlockRowDTO:
        """Create an instance of BlockRowDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BlockRowDTO.parse_obj(obj)

        _obj = BlockRowDTO.parse_obj({
            "type": obj.get("type"),
            "blocks": [IndicatorLinkDTO.from_dict(_item) for _item in obj.get("blocks")] if obj.get("blocks") is not None else None
        })
        return _obj


