# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, conlist, constr, validator

class DefaultValuesIndicatorDTO(BaseModel):
    """
    DefaultValuesIndicatorDTO
    """
    values: Optional[conlist(Union[StrictFloat, StrictInt], max_items=2, min_items=2)] = None
    breaks: Optional[conlist(Union[StrictFloat, StrictInt], min_items=1)] = None
    display_intervals: Optional[conlist(StrictInt)] = Field(default=None, alias="displayIntervals")
    granularity: Optional[constr(strict=True)] = None
    __properties = ["values", "breaks", "displayIntervals", "granularity"]

    @validator('granularity')
    def granularity_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\/rest\/projects\/(\$projectId|[a-z0-9]{16})\/md\/datasets(\?name=[a-z0-9_-]+|\/[a-z0-9]+)$", value):
            raise ValueError(r"must validate the regular expression /^\/rest\/projects\/(\$projectId|[a-z0-9]{16})\/md\/datasets(\?name=[a-z0-9_-]+|\/[a-z0-9]+)$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DefaultValuesIndicatorDTO:
        """Create an instance of DefaultValuesIndicatorDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DefaultValuesIndicatorDTO:
        """Create an instance of DefaultValuesIndicatorDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DefaultValuesIndicatorDTO.parse_obj(obj)

        _obj = DefaultValuesIndicatorDTO.parse_obj({
            "values": obj.get("values"),
            "breaks": obj.get("breaks"),
            "display_intervals": obj.get("displayIntervals"),
            "granularity": obj.get("granularity")
        })
        return _obj


