# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, List, Optional
from pydantic import BaseModel, conlist, constr, validator
from openapi_client.models.center_dto import CenterDTO

class DefaultSelectedDTO(BaseModel):
    """
    DefaultSelectedDTO
    """
    dataset: Optional[constr(strict=True)] = None
    ids: Optional[conlist(Any)] = None
    coordinates: Optional[conlist(CenterDTO)] = None
    __properties = ["dataset", "ids", "coordinates"]

    @validator('dataset')
    def dataset_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\/rest\/projects\/(\$projectId|[a-z0-9]{16})\/md\/datasets(\?name=[a-z0-9_-]+|\/[a-z0-9]+)$", value):
            raise ValueError(r"must validate the regular expression /^\/rest\/projects\/(\$projectId|[a-z0-9]{16})\/md\/datasets(\?name=[a-z0-9_-]+|\/[a-z0-9]+)$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DefaultSelectedDTO:
        """Create an instance of DefaultSelectedDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in coordinates (list)
        _items = []
        if self.coordinates:
            for _item in self.coordinates:
                if _item:
                    _items.append(_item.to_dict())
            _dict['coordinates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DefaultSelectedDTO:
        """Create an instance of DefaultSelectedDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DefaultSelectedDTO.parse_obj(obj)

        _obj = DefaultSelectedDTO.parse_obj({
            "dataset": obj.get("dataset"),
            "ids": obj.get("ids"),
            "coordinates": [CenterDTO.from_dict(_item) for _item in obj.get("coordinates")] if obj.get("coordinates") is not None else None
        })
        return _obj


