# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, validator
from openapi_client.models.attribute_format_dto import AttributeFormatDTO

class FeatureAttributeDTO(BaseModel):
    """
    FeatureAttributeDTO
    """
    type: StrictStr = Field(...)
    value: StrictStr = Field(...)
    format: Optional[AttributeFormatDTO] = None
    layout: Optional[StrictStr] = None
    __properties = ["type", "value", "format", "layout"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('property', 'expression'):
            raise ValueError("must be one of enum values ('property', 'expression')")
        return value

    @validator('layout')
    def layout_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('primary', 'secondary'):
            raise ValueError("must be one of enum values ('primary', 'secondary')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FeatureAttributeDTO:
        """Create an instance of FeatureAttributeDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of format
        if self.format:
            _dict['format'] = self.format.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FeatureAttributeDTO:
        """Create an instance of FeatureAttributeDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FeatureAttributeDTO.parse_obj(obj)

        _obj = FeatureAttributeDTO.parse_obj({
            "type": obj.get("type") if obj.get("type") is not None else 'property',
            "value": obj.get("value"),
            "format": AttributeFormatDTO.from_dict(obj.get("format")) if obj.get("format") is not None else None,
            "layout": obj.get("layout")
        })
        return _obj


