# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, constr, validator

class GoogleStreetViewDTO(BaseModel):
    """
    GoogleStreetViewDTO
    """
    type: Optional[constr(strict=True)] = None
    __properties = ["type"]

    @validator('type')
    def type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^googleStreetView$", value):
            raise ValueError(r"must validate the regular expression /^googleStreetView$/")
        return value

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('googleStreetView'):
            raise ValueError("must be one of enum values ('googleStreetView')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GoogleStreetViewDTO:
        """Create an instance of GoogleStreetViewDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GoogleStreetViewDTO:
        """Create an instance of GoogleStreetViewDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GoogleStreetViewDTO.parse_obj(obj)

        _obj = GoogleStreetViewDTO.parse_obj({
            "type": obj.get("type")
        })
        return _obj


