# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, constr, validator
from openapi_client.models.format_dto import FormatDTO

class HistogramFilterDTO(BaseModel):
    """
    HistogramFilterDTO
    """
    type: constr(strict=True) = Field(...)
    var_property: StrictStr = Field(default=..., alias="property")
    format: Optional[FormatDTO] = None
    __properties = ["type", "property", "format"]

    @validator('type')
    def type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^histogram$", value):
            raise ValueError(r"must validate the regular expression /^histogram$/")
        return value

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('histogram'):
            raise ValueError("must be one of enum values ('histogram')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> HistogramFilterDTO:
        """Create an instance of HistogramFilterDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of format
        if self.format:
            _dict['format'] = self.format.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> HistogramFilterDTO:
        """Create an instance of HistogramFilterDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return HistogramFilterDTO.parse_obj(obj)

        _obj = HistogramFilterDTO.parse_obj({
            "type": obj.get("type"),
            "var_property": obj.get("property"),
            "format": FormatDTO.from_dict(obj.get("format")) if obj.get("format") is not None else None
        })
        return _obj


