# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist, constr, validator
from openapi_client.models.indicator_link_dto_block_rows_inner import IndicatorLinkDTOBlockRowsInner

class IndicatorLinkDTO(BaseModel):
    """
    IndicatorLinkDTO
    """
    type: constr(strict=True) = Field(...)
    title: Optional[constr(strict=True, max_length=255)] = None
    indicator: constr(strict=True) = Field(...)
    indicator_drill: constr(strict=True) = Field(default=..., alias="indicatorDrill")
    layout: Optional[StrictStr] = None
    collapsed: Optional[StrictBool] = None
    block_rows: Optional[conlist(IndicatorLinkDTOBlockRowsInner)] = Field(default=None, alias="blockRows")
    __properties = ["type", "title", "indicator", "indicatorDrill", "layout", "collapsed", "blockRows"]

    @validator('type')
    def type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^indicator$", value):
            raise ValueError(r"must validate the regular expression /^indicator$/")
        return value

    @validator('indicator')
    def indicator_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\/rest\/projects\/(\$projectId|[a-z0-9]{16})\/md\/indicators(\?name=[a-z0-9_-]+|\/[a-z0-9]+)$", value):
            raise ValueError(r"must validate the regular expression /^\/rest\/projects\/(\$projectId|[a-z0-9]{16})\/md\/indicators(\?name=[a-z0-9_-]+|\/[a-z0-9]+)$/")
        return value

    @validator('indicator_drill')
    def indicator_drill_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\/rest\/projects\/(\$projectId|[a-z0-9]{16})\/md\/indicatorDrills(\?name=[a-z0-9_-]+|\/[a-z0-9]+)$", value):
            raise ValueError(r"must validate the regular expression /^\/rest\/projects\/(\$projectId|[a-z0-9]{16})\/md\/indicatorDrills(\?name=[a-z0-9_-]+|\/[a-z0-9]+)$/")
        return value

    @validator('layout')
    def layout_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('primary', 'secondary'):
            raise ValueError("must be one of enum values ('primary', 'secondary')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IndicatorLinkDTO:
        """Create an instance of IndicatorLinkDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in block_rows (list)
        _items = []
        if self.block_rows:
            for _item in self.block_rows:
                if _item:
                    _items.append(_item.to_dict())
            _dict['blockRows'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IndicatorLinkDTO:
        """Create an instance of IndicatorLinkDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IndicatorLinkDTO.parse_obj(obj)

        _obj = IndicatorLinkDTO.parse_obj({
            "type": obj.get("type"),
            "title": obj.get("title"),
            "indicator": obj.get("indicator"),
            "indicator_drill": obj.get("indicatorDrill"),
            "layout": obj.get("layout"),
            "collapsed": obj.get("collapsed"),
            "block_rows": [IndicatorLinkDTOBlockRowsInner.from_dict(_item) for _item in obj.get("blockRows")] if obj.get("blockRows") is not None else None
        })
        return _obj


