# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel, Field, StrictInt

class MandatoryKeysForPagableResponse(BaseModel):
    """
    define keys links and page that are mandatory for all pageble responses  # noqa: E501
    """
    size: StrictInt = Field(...)
    total_elements: Optional[Any] = Field(default=..., alias="totalElements")
    total_pages: StrictInt = Field(default=..., alias="totalPages")
    number: StrictInt = Field(...)
    __properties = ["size", "totalElements", "totalPages", "number"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MandatoryKeysForPagableResponse:
        """Create an instance of MandatoryKeysForPagableResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if total_elements (nullable) is None
        # and __fields_set__ contains the field
        if self.total_elements is None and "total_elements" in self.__fields_set__:
            _dict['totalElements'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MandatoryKeysForPagableResponse:
        """Create an instance of MandatoryKeysForPagableResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MandatoryKeysForPagableResponse.parse_obj(obj)

        _obj = MandatoryKeysForPagableResponse.parse_obj({
            "size": obj.get("size"),
            "total_elements": obj.get("totalElements"),
            "total_pages": obj.get("totalPages"),
            "number": obj.get("number")
        })
        return _obj


