# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from openapi_client.models.cuzk_parcel_info_dto import CuzkParcelInfoDTO
from openapi_client.models.google_earth_dto import GoogleEarthDTO
from openapi_client.models.google_satellite_dto import GoogleSatelliteDTO
from openapi_client.models.google_street_view_dto import GoogleStreetViewDTO
from openapi_client.models.mapycz_ortophoto_dto import MapyczOrtophotoDTO
from openapi_client.models.mapycz_panorama_dto import MapyczPanoramaDTO
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

MAPCONTEXTMENUITEMABSTRACTTYPE_ONE_OF_SCHEMAS = ["CuzkParcelInfoDTO", "GoogleEarthDTO", "GoogleSatelliteDTO", "GoogleStreetViewDTO", "MapyczOrtophotoDTO", "MapyczPanoramaDTO"]

class MapContextMenuItemAbstractType(BaseModel):
    """
    MapContextMenuItemAbstractType
    """
    # data type: GoogleSatelliteDTO
    oneof_schema_1_validator: Optional[GoogleSatelliteDTO] = None
    # data type: GoogleStreetViewDTO
    oneof_schema_2_validator: Optional[GoogleStreetViewDTO] = None
    # data type: GoogleEarthDTO
    oneof_schema_3_validator: Optional[GoogleEarthDTO] = None
    # data type: MapyczPanoramaDTO
    oneof_schema_4_validator: Optional[MapyczPanoramaDTO] = None
    # data type: MapyczOrtophotoDTO
    oneof_schema_5_validator: Optional[MapyczOrtophotoDTO] = None
    # data type: CuzkParcelInfoDTO
    oneof_schema_6_validator: Optional[CuzkParcelInfoDTO] = None
    if TYPE_CHECKING:
        actual_instance: Union[CuzkParcelInfoDTO, GoogleEarthDTO, GoogleSatelliteDTO, GoogleStreetViewDTO, MapyczOrtophotoDTO, MapyczPanoramaDTO]
    else:
        actual_instance: Any
    one_of_schemas: List[str] = Field(MAPCONTEXTMENUITEMABSTRACTTYPE_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = MapContextMenuItemAbstractType.construct()
        error_messages = []
        match = 0
        # validate data type: GoogleSatelliteDTO
        if not isinstance(v, GoogleSatelliteDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GoogleSatelliteDTO`")
        else:
            match += 1
        # validate data type: GoogleStreetViewDTO
        if not isinstance(v, GoogleStreetViewDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GoogleStreetViewDTO`")
        else:
            match += 1
        # validate data type: GoogleEarthDTO
        if not isinstance(v, GoogleEarthDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GoogleEarthDTO`")
        else:
            match += 1
        # validate data type: MapyczPanoramaDTO
        if not isinstance(v, MapyczPanoramaDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MapyczPanoramaDTO`")
        else:
            match += 1
        # validate data type: MapyczOrtophotoDTO
        if not isinstance(v, MapyczOrtophotoDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MapyczOrtophotoDTO`")
        else:
            match += 1
        # validate data type: CuzkParcelInfoDTO
        if not isinstance(v, CuzkParcelInfoDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CuzkParcelInfoDTO`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in MapContextMenuItemAbstractType with oneOf schemas: CuzkParcelInfoDTO, GoogleEarthDTO, GoogleSatelliteDTO, GoogleStreetViewDTO, MapyczOrtophotoDTO, MapyczPanoramaDTO. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in MapContextMenuItemAbstractType with oneOf schemas: CuzkParcelInfoDTO, GoogleEarthDTO, GoogleSatelliteDTO, GoogleStreetViewDTO, MapyczOrtophotoDTO, MapyczPanoramaDTO. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> MapContextMenuItemAbstractType:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> MapContextMenuItemAbstractType:
        """Returns the object represented by the json string"""
        instance = MapContextMenuItemAbstractType.construct()
        error_messages = []
        match = 0

        # deserialize data into GoogleSatelliteDTO
        try:
            instance.actual_instance = GoogleSatelliteDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GoogleStreetViewDTO
        try:
            instance.actual_instance = GoogleStreetViewDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GoogleEarthDTO
        try:
            instance.actual_instance = GoogleEarthDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MapyczPanoramaDTO
        try:
            instance.actual_instance = MapyczPanoramaDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MapyczOrtophotoDTO
        try:
            instance.actual_instance = MapyczOrtophotoDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CuzkParcelInfoDTO
        try:
            instance.actual_instance = CuzkParcelInfoDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into MapContextMenuItemAbstractType with oneOf schemas: CuzkParcelInfoDTO, GoogleEarthDTO, GoogleSatelliteDTO, GoogleStreetViewDTO, MapyczOrtophotoDTO, MapyczPanoramaDTO. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into MapContextMenuItemAbstractType with oneOf schemas: CuzkParcelInfoDTO, GoogleEarthDTO, GoogleSatelliteDTO, GoogleStreetViewDTO, MapyczOrtophotoDTO, MapyczPanoramaDTO. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())


