# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class TokenResponseDTO(BaseModel):
    """
    TokenResponseDTO
    """
    token_type: Optional[StrictStr] = None
    expires_in: Optional[StrictInt] = None
    access_token: StrictStr = Field(...)
    scope: Optional[StrictStr] = None
    refresh_token: Optional[StrictStr] = None
    id_token: Optional[StrictStr] = None
    __properties = ["token_type", "expires_in", "access_token", "scope", "refresh_token", "id_token"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TokenResponseDTO:
        """Create an instance of TokenResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TokenResponseDTO:
        """Create an instance of TokenResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TokenResponseDTO.parse_obj(obj)

        _obj = TokenResponseDTO.parse_obj({
            "token_type": obj.get("token_type"),
            "expires_in": obj.get("expires_in"),
            "access_token": obj.get("access_token"),
            "scope": obj.get("scope"),
            "refresh_token": obj.get("refresh_token"),
            "id_token": obj.get("id_token")
        })
        return _obj


